import java.sql.*;
import javax.swing.*;
import net.proteanit.sql.DbUtils;


public class cabInformation extends javax.swing.JFrame {
       Connection conn = null;
       ResultSet rs = null;
       PreparedStatement pst = null;

    /** Creates new form cabInformation */

    public cabInformation() {
        initComponents();
        conn = javaConnect.ConnectDb();
        
        setVisible(true);
    }

    public void update_dataBase(adminitrator a){
        try{
            String sql = "Insert into Administrator(VehicleType,DriverName,VehicleRegNo,VehicleMaintainanceDetails,DistanceRun,VehicleSeatingCapacity) values (?,?,?,?,?,?)";
            pst = conn.prepareStatement(sql);
            pst.setString(1, a.vType.getSelectedItem());
            pst.setString(2, a.txtDriver.getText());
            pst.setInt(3, Integer.parseInt(a.txtRno.getText()));
            pst.setString(4,  a.txtMdetails.getText());
            pst.setInt(5, Integer.parseInt(a.txtKms.getText()));
            pst.setInt(6, Integer.parseInt(a.seatCap.getSelectedItem()));
            //pst.setInt(9, )

            //`JOptionPane.showMessageDialog(null, "Saved");
            pst.execute();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public void update_table()
    {
        try{

            String sql = "Select * from Administrator";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            Table_cab.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "not done");
        }
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Table_cab = new javax.swing.JTable();
        ok = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Table_cab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table_cab.setName("Table_cab"); // NOI18N
        jScrollPane1.setViewportView(Table_cab);

        ok.setText("Add More");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(ok)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(ok)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
            this.setVisible(false);
    }//GEN-LAST:event_okActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table_cab;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton ok;
    // End of variables declaration//GEN-END:variables



}
